In [2]:
import pandas as pd

In [3]:
file_path= "data/TypeCharts_20250107_forPublication.xlsx"

df = pd.read_excel(file_path, sheet_name = "type_data", header = 1)

In [4]:
df.head()

,Date,Unnamed: 1,Spacecraft,Rocket Bodies,Mission-Related Debris,Fragmentation Debris,Unassigned Type,Total,Unnamed: 8,Spacecraft.1,...,Total.1,Unnamed: 14,Spacecraft.2,Rocket Bodies.2,Mission-Related Debris.2,Fragmentation Debris.2,Total.2,Unnamed: 20,Monthly total of objects in orbit by object TYPE (including STS):,Unnamed: 22
0,NaN,num,NaN,NaN,NaN,NaN,NaN,NaN,mass,NaN,...,NaN,"mass (metric tons, do not paste here)",NaN,NaN,NaN,NaN,NaN,NaN,epoch is -->,1957-01-01
1,1957.00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,catalog of -->,2025-01-07
2,1957.09,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaT
3,1957.16,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,Number of objects to left.,NaT
4,1957.25,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,Mass of objects (kg) in center.,NaT

In [5]:
df.tail(10)

,Date,Unnamed: 1,Spacecraft,Rocket Bodies,Mission-Related Debris,Fragmentation Debris,Unassigned Type,Total,Unnamed: 8,Spacecraft.1,...,Total.1,Unnamed: 14,Spacecraft.2,Rocket Bodies.2,Mission-Related Debris.2,Fragmentation Debris.2,Total.2,Unnamed: 20,Monthly total of objects in orbit by object TYPE (including STS):,Unnamed: 22
807,2024.17,NaN,12283.0,2139.0,1932.0,11642.0,532.0,28528.0,NaN,7786300.0,...,11786620.38,NaN,7786.3,3665.9,141.36,193.06038,11786.62038,NaN,NaN,NaT
808,2024.25,NaN,12445.0,2135.0,1927.0,11593.0,537.0,28637.0,NaN,7925600.0,...,11914249.68,NaN,7925.6,3655.3,137.90,195.44968,11914.24968,NaN,NaN,NaT
809,2024.33,NaN,12640.0,2128.0,1916.0,11526.0,552.0,28762.0,NaN,8076100.0,...,12047348.98,NaN,8076.1,3637.9,137.90,195.44898,12047.34898,NaN,NaN,NaT
810,2024.42,NaN,12752.0,2130.0,1903.0,11498.0,548.0,28831.0,NaN,8203400.0,...,12180058.28,NaN,8203.4,3640.4,134.92,201.33828,12180.05828,NaN,NaN,NaT
811,2024.50,NaN,12784.0,2123.0,1897.0,11445.0,544.0,28793.0,NaN,8265200.0,...,12227456.88,NaN,8265.2,3626.0,134.92,201.33688,12227.45688,NaN,NaN,NaT
812,2024.58,NaN,13032.0,2128.0,1888.0,12064.0,563.0,29675.0,NaN,8385700.0,...,12352146.84,NaN,8385.7,3629.0,134.91,202.53684,12352.14684,NaN,NaN,NaT
813,2024.67,NaN,13046.0,2124.0,1895.0,12015.0,572.0,29652.0,NaN,8468800.0,...,12430836.83,NaN,8468.8,3620.9,136.39,204.74683,12430.83683,NaN,NaN,NaT
814,2024.75,NaN,13151.0,2129.0,1890.0,11972.0,563.0,29705.0,NaN,8557300.0,...,12534676.12,NaN,8557.3,3634.3,134.91,208.16612,12534.67612,NaN,NaN,NaT
815,2024.84,NaN,13357.0,2137.0,1889.0,11900.0,629.0,29912.0,NaN,8760500.0,...,12756275.42,NaN,8760.5,3654.5,134.91,206.36542,12756.27542,NaN,NaN,NaT
816,2024.92,NaN,13449.0,2136.0,1877.0,11791.0,621.0,29874.0,NaN,8844400.0,...,12827794.71,NaN,8844.4,3649.5,133.43,200.46471,12827.79471,NaN,NaN,NaT

In [6]:
c = df.copy()

In [7]:
c.head(10)

,Date,Unnamed: 1,Spacecraft,Rocket Bodies,Mission-Related Debris,Fragmentation Debris,Unassigned Type,Total,Unnamed: 8,Spacecraft.1,...,Total.1,Unnamed: 14,Spacecraft.2,Rocket Bodies.2,Mission-Related Debris.2,Fragmentation Debris.2,Total.2,Unnamed: 20,Monthly total of objects in orbit by object TYPE (including STS):,Unnamed: 22
0,NaN,num,NaN,NaN,NaN,NaN,NaN,NaN,mass,NaN,...,NaN,"mass (metric tons, do not paste here)",NaN,NaN,NaN,NaN,NaN,NaN,epoch is -->,1957-01-01
1,1957.00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,catalog of -->,2025-01-07
2,1957.09,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaT
3,1957.16,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,Number of objects to left.,NaT
4,1957.25,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,Mass of objects (kg) in center.,NaT
5,1957.33,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaT
6,1957.42,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,Mass data to -->,2024-12-31
7,1957.50,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaT
8,1957.58,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaT
9,1957.67,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaT

In [8]:
c.sort_values("Date")

,Date,Unnamed: 1,Spacecraft,Rocket Bodies,Mission-Related Debris,Fragmentation Debris,Unassigned Type,Total,Unnamed: 8,Spacecraft.1,...,Total.1,Unnamed: 14,Spacecraft.2,Rocket Bodies.2,Mission-Related Debris.2,Fragmentation Debris.2,Total.2,Unnamed: 20,Monthly total of objects in orbit by object TYPE (including STS):,Unnamed: 22
1,1957.00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.00,NaN,0.0,0.0,0.00,0.00000,0.00000,NaN,catalog of -->,2025-01-07
2,1957.09,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.00,NaN,0.0,0.0,0.00,0.00000,0.00000,NaN,NaN,NaT
3,1957.16,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.00,NaN,0.0,0.0,0.00,0.00000,0.00000,NaN,Number of objects to left.,NaT
4,1957.25,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.00,NaN,0.0,0.0,0.00,0.00000,0.00000,NaN,Mass of objects (kg) in center.,NaT
5,1957.33,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.00,NaN,0.0,0.0,0.00,0.00000,0.00000,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813,2024.67,NaN,13046.0,2124.0,1895.0,12015.0,572.0,29652.0,NaN,8468800.0,...,12430836.83,NaN,8468.8,3620.9,136.39,204.74683,12430.83683,NaN,NaN,NaT
814,2024.75,NaN,13151.0,2129.0,1890.0,11972.0,563.0,29705.0,NaN,8557300.0,...,12534676.12,NaN,8557.3,3634.3,134.91,208.16612,12534.67612,NaN,NaN,NaT
815,2024.84,NaN,13357.0,2137.0,1889.0,11900.0,629.0,29912.0,NaN,8760500.0,...,12756275.42,NaN,8760.5,3654.5,134.91,206.36542,12756.27542,NaN,NaN,NaT
816,2024.92,NaN,13449.0,2136.0,1877.0,11791.0,621.0,29874.0,NaN,8844400.0,...,12827794.71,NaN,8844.4,3649.5,133.43,200.46471,12827.79471,NaN,NaN,NaT
0,NaN,num,NaN,NaN,NaN,NaN,NaN,NaN,mass,NaN,...,NaN,"mass (metric tons, do not paste here)",NaN,NaN,NaN,NaN,NaN,NaN,epoch is -->,1957-01-01

FILTERING

In [9]:
c.info()

<class 'pandas.DataFrame'>
RangeIndex: 817 entries, 0 to 816
Data columns (total 23 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   Date                                                               816 non-null    float64
 1   Unnamed: 1                                                         1 non-null      str
 2   Spacecraft                                                         816 non-null    float64
 3   Rocket Bodies                                                      816 non-null    float64
 4   Mission-Related Debris                                             816 non-null    float64
 5   Fragmentation Debris                                               816 non-null    float64
 6   Unassigned Type                                                    816 non-null    float64
 7   Total                                                              816 non-null    float64
 8   Unnamed: 8                                                         1 non-null      str
 9   Spacecraft.1                                                       816 non-null    float64
 10  Rocket Bodies.1                                                    816 non-null    float64
 11  Mission-Related Debris.1                                           816 non-null    float64
 12  Fragmentation Debris.1                                             816 non-null    float64
 13  Total.1                                                            816 non-null    float64
 14  Unnamed: 14                                                        1 non-null      str
 15  Spacecraft.2                                                       816 non-null    float64
 16  Rocket Bodies.2                                                    816 non-null    float64
 17  Mission-Related Debris.2                                           816 non-null    float64
 18  Fragmentation Debris.2                                             816 non-null    float64
 19  Total.2                                                            816 non-null    float64
 20  Unnamed: 20                                                        0 non-null      float64
 21  Monthly total of objects in orbit by object TYPE (including STS):  5 non-null      str
 22  Unnamed: 22                                                        3 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(18), str(4)
memory usage: 146.9 KB

In [15]:
c.loc[1:10, ["Date", "Spacecraft"]]

       Date  Spacecraft
1   1957.00         0.0
2   1957.09         0.0
3   1957.16         0.0
4   1957.25         0.0
5   1957.33         0.0
6   1957.42         0.0
7   1957.50         0.0
8   1957.58         0.0
9   1957.67         0.0
10  1957.75         1.0

In [16]:
c[c["Date"]<2000]

,Date,Unnamed: 1,Spacecraft,Rocket Bodies,Mission-Related Debris,Fragmentation Debris,Unassigned Type,Total,Unnamed: 8,Spacecraft.1,...,Total.1,Unnamed: 14,Spacecraft.2,Rocket Bodies.2,Mission-Related Debris.2,Fragmentation Debris.2,Total.2,Unnamed: 20,Monthly total of objects in orbit by object TYPE (including STS):,Unnamed: 22
1,1957.00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.000,NaN,0.0,0.0,0.000000,0.00000,0.000000,NaN,catalog of -->,2025-01-07
2,1957.09,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.000,NaN,0.0,0.0,0.000000,0.00000,0.000000,NaN,NaN,NaT
3,1957.16,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.000,NaN,0.0,0.0,0.000000,0.00000,0.000000,NaN,Number of objects to left.,NaT
4,1957.25,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.000,NaN,0.0,0.0,0.000000,0.00000,0.000000,NaN,Mass of objects (kg) in center.,NaT
5,1957.33,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,0.000,NaN,0.0,0.0,0.000000,0.00000,0.000000,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,1999.58,NaN,2569.0,1472.0,1693.0,5157.0,1.0,10892.0,NaN,2643200.0,...,4846352.873,NaN,2643.2,2039.8,22.656963,140.69591,4846.352873,NaN,NaN,NaT
513,1999.67,NaN,2581.0,1482.0,1699.0,5141.0,1.0,10904.0,NaN,2660500.0,...,4888566.786,NaN,2660.5,2063.0,24.370876,140.69591,4888.566786,NaN,NaN,NaT
514,1999.75,NaN,2589.0,1480.0,1693.0,5167.0,1.0,10930.0,NaN,2662100.0,...,4882555.010,NaN,2662.1,2056.0,22.349100,142.10591,4882.555010,NaN,NaN,NaT
515,1999.84,NaN,2591.0,1480.0,1685.0,5159.0,1.0,10916.0,NaN,2663400.0,...,4891835.010,NaN,2663.4,2061.0,22.179100,145.25591,4891.835010,NaN,NaN,NaT
516,1999.92,NaN,2606.0,1480.0,1682.0,5134.0,1.0,10903.0,NaN,2757700.0,...,4988292.010,NaN,2757.7,2063.0,22.276100,145.31591,4988.292010,NaN,NaN,NaT